# Generated by Django 3.1.3 on 2021-03-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SshHostKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(max_length=200, unique=True)),
                ('host_key', models.TextField()),
            ],
        ),
    ]
